export enum Colour {
  None = "none",
  Black = "black",
  Blue = "blue",
  DarkBlue = "dark-blue",
  DarkGreen = "dark-green",
  DarkRed = "dark-red",
  Green = "green",
  LightBlue = "light-blue",
  Orange = "orange",
  Purple = "purple",
  Red = "red",
  White = "white",
  Yellow = "yellow",
}
